#!/usr/bin/with-contenv bash

set -e

function log {
  echo `date` $ME - $@
}

function run_connector {
  exec ${SERVICE_HOME}/bin/connect-distributed ${SERVICE_HOME}/conf/connect-avro.properties
}

while [ ! -f "${SERVICE_HOME}/conf/connect-avro.properties" ]; do
  log "[ Waiting for configuration ... ]"
  sleep 1
done

log "[ Running Kafka Connector ... ]"
run_connector
